export const majorOptions = [
  { value: 0, label: 'IT공학전공' },
  { value: 1, label: '가족자원경영학과' },
  { value: 2, label: '경영학부' },
  { value: 3, label: '경제학부' },
  { value: 4, label: '공공인재학전공' },
  { value: 5, label: '공예과' },
  { value: 6, label: '관현악과' },
  { value: 7, label: '교육학부' },
  { value: 8, label: '국제한국어교육전공' },
  { value: 9, label: '글로벌비즈니스개발학전공' },
  { value: 10, label: '글로벌지식경영전공' },
  { value: 11, label: '글로벌협력전공' },
  { value: 12, label: '글로벌환경학전공' },
  { value: 13, label: '금용공학전공' },
  { value: 14, label: '기계시스템학부' },
  { value: 15, label: '기술인문융합전공' },
  { value: 16, label: '기업법무전공' },
  { value: 17, label: '기초공학부' },
  { value: 18, label: '나노물리학과' },
  { value: 19, label: '독일언어.문화학과' },
  { value: 20, label: '르꼬르동블루외식경영전공' },
  { value: 21, label: '무용과' },
  { value: 22, label: '문헌정보학과' },
  { value: 23, label: '문화관광학전공' },
  { value: 24, label: '문화예술기획전공' },
  { value: 25, label: '미디어학부' },
  { value: 26, label: '법학부' },
  { value: 27, label: '비서학전공' },
  { value: 28, label: '빅데이터분석학' },
  { value: 29, label: '사회심리학과' },
  { value: 30, label: '산업디자인과' },
  { value: 31, label: '상담학전공' },
  { value: 32, label: '생명시스템학부' },
  { value: 33, label: '성악과' },
  { value: 34, label: '세무회계학전공' },
  { value: 35, label: '소비자경제학과' },
  { value: 36, label: '소프트웨어융합전공' },
  { value: 37, label: '수학과' },
  { value: 38, label: '순헌융합인문학전공' },
  { value: 39, label: '스토리텔링전공' },
  { value: 40, label: '시각.영상 디자인과' },
  { value: 41, label: '식품영양학과' },
  { value: 42, label: '아동복지학부' },
  { value: 43, label: '앙트러프러너십전공' },
  { value: 44, label: '약학부' },
  { value: 45, label: '역사문화학과' },
  { value: 46, label: '영어영문학전공' },
  { value: 47, label: '응용물리전공' },
  { value: 48, label: '의류학과' },
  { value: 49, label: '인재개발전공' },
  { value: 50, label: '일본학과' },
  { value: 51, label: '작곡과' },
  { value: 52, label: '전자공학전공' },
  { value: 53, label: '정치외교학과' },
  { value: 54, label: '중어중문학부' },
  { value: 55, label: '체육교육과' },
  { value: 56, label: '컴퓨터과학전공' },
  { value: 57, label: '테슬(TESL)전공' },
  { value: 58, label: '통계학과' },
  { value: 59, label: '통상학전공' },
  { value: 60, label: '프랑스언어.문화학과' },
  { value: 61, label: '피아노과' },
  { value: 62, label: '한국어문화부' },
  { value: 63, label: '행정학과' },
  { value: 64, label: '홍보광고학과' },
  { value: 65, label: '화공생명공학부' },
  { value: 66, label: '화학과' },
  { value: 67, label: '환경디자인과' },
  { value: 68, label: '회화과' },
];

export const adminVote = [
  { value: 'official', label: '공식 행사 투표' },
  { value: 'free', label: '자유 투표' },
  { value: 'group', label: '단체' },
];
export const memberVote = [
  { value: 'free', label: '자유 투표' },
  { value: 'group', label: '단체' },
];

export const FreeVoteCategory = [
  { value: 0, label: '일상' },
  { value: 1, label: '공부' },
  { value: 2, label: '취업' },
  { value: 3, label: '연예' },
  { value: 4, label: '정치' },
  { value: 5, label: '기타' },
];

export const groupCategory = [
  { value: 'club', label: '동아리' },
  { value: 'major', label: '학부/학과' },
  { value: 'class', label: '수업' },
  { value: 'etc', label: '기타' },
];

export const sortTypes = [
  { value: 'recent', label: '최신순' },
  { value: 'popular', label: '인기순' },
];

export const joinPolicy = [
  { value: 'accept', label: '모든 가입 수락' },
  { value: 'filter', label: '승인 후 가입 수락' },
];

export const groupSort = [
  { value: 'all', label: '전체' },
  { value: 'club', label: '동아리' },
  { value: 'major', label: '학부/학과' },
  { value: 'class', label: '수업' },
  { value: 'etc', label: '기타' },
];
