export const authConstants = {
  SIGNUP_REQUEST: 'user/SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'user/SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'user/SIGNUP_FAILURE',

  SIGNIN_REQUEST: 'user/SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'user/SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'user/SIGNIN_FAILURE',

  SET_USER_TEMP: 'user/SET_USER_TEMP',

  EDIT_REQUEST: 'user/EDIT_REQUEST',
  EDIT_SUCCESS: 'user/EDIT_SUCCESS',
  EDIT_FAILURE: 'user/EDIT_FAILURE',
  LOGOUT: 'user/LOGOUT',
};
