export const groupConstants = {
  CREATE_GROUP_REQUEST: 'CREATE_GROUP_REQUEST',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_FAILURE: 'CREATE_GROUP_FAILURE',

  ALL_GROUP_LOAD_REQUEST: 'ALL_GROUP_LOAD_REQUEST',
  ALL_GROUP_LOAD_SUCCESS: 'ALL_GROUP_LOAD_SUCCESS',
  ALL_GROUP_LOAD_FAILURE: 'ALL_GROUP_LOAD_FAILURE',

  ID_GROUP_LOAD_REQUEST: 'ID_GROUP_LOAD_REQUEST',
  ID_GROUP_LOAD_SUCCESS: 'ID_GROUP_LOAD_SUCCESS',
  ID_GROUP_LOAD_FAILURE: 'ID_GROUP_LOAD_FAILURE',

  UNLOAD_GROUP: 'UNLOAD_GROUP',
  UNLOAD_GROUP_NOTICE: 'UNLOAD_GROUP_NOTICE',

  ID_NOTICE_LOAD_REQUEST: 'ID_NOTICE_LOAD_REQUEST',
  ID_NOTICE_LOAD_SUCCESS: 'ID_NOTICE_LOAD_SUCCESS',
  ID_NOTICE_LOAD_FAILURE: 'ID_NOTICE_LOAD_FAILURE',

  MODIFY_NOTICE: 'MODIFY_NOTICE',

  REMOVE_NOTICE: 'REMOVE_NOTICE',
};
