export const myPageConstants = {
  PARTICIPATED_VOTE_LOAD_REQUEST: 'PARTICIPATED_VOTE_LOAD_REQUEST',
  PARTICIPATED_VOTE_LOAD_SUCCESS: 'PARTICIPATED_VOTE_LOAD_SUCCESS',
  PARTICIPATED_VOTE_LOAD_FAILURE: 'PARTICIPATED_VOTE_LOAD_FAILURE',

  USER_GROUP_LOAD_REQUEST: 'USER_GROUP_LOAD_REQUEST',
  USER_GROUP_LOAD_SUCCESS: 'USER_GROUP_LOAD_SUCCESS',
  USER_GROUP_LOAD_FAILURE: 'USER_GROUP_LOAD_FAILURE',

  USER_GROUP_LEAVE_REQUEST: 'USER_GROUP_LEAVE_REQUEST',
  USER_GROUP_LEAVE_SUCCESS: 'USER_GROUP_LEAVE_SUCCESS',
  USER_GROUP_LEAVE_FAILURE: 'USER_GROUP_LEAVE_FAILURE',
};
