export const voteConstants = {
  ALL_VOTE_LOAD_REQUEST: 'ALL_VOTE_LOAD_REQUEST',
  ALL_VOTE_LOAD_SUCCESS: 'ALL_VOTE_LOAD_SUCCESS',
  ALL_VOTE_LOAD_FAILURE: 'ALL_VOTE_LOAD_FAILURE',

  UNLOAD_VOTE: 'UNLOAD_VOTE',

  ID_VOTE_LOAD_REQUEST: 'ID_VOTE_LOAD_REQUEST',
  ID_VOTE_LOAD_SUCCESS: 'ID_VOTE_LOAD_SUCCESS',
  ID_VOTE_LOAD_FAILURE: 'ID_VOTE_LOAD_FAILURE',

  CLOSED_ID_VOTE_LOAD_REQUEST: 'CLOSED_ID_VOTE_LOAD_REQUEST',
  CLOSED_ID_VOTE_LOAD_SUCCESS: 'CLOSED_ID_VOTE_LOAD_SUCCESS',
  CLOSED_ID_VOTE_LOAD_FAILURE: 'CLOSED_ID_VOTE_LOAD_FAILURE',

  INSERT_VOTE: 'INSERT_VOTE',
  REMOVE_VOTE: 'REMOVE_VOTE',
};
