export const voteConstants = {
  ALL_VOTE_LOAD_REQUEST: 'ALL_VOTE_LOAD_REQUEST',
  ALL_VOTE_LOAD_SUCCESS: 'ALL_VOTE_LOAD_SUCCESS',
  ALL_VOTE_LOAD_FAILURE: 'ALL_VOTE_LOAD_FAILURE',

  UNLOAD_VOTE: 'UNLOAD_VOTE',

  ID_VOTE_LOAD_REQUEST: 'ID_VOTE_LOAD_REQUEST',
  ID_VOTE_LOAD_SUCCESS: 'ID_VOTE_LOAD_SUCCESS',
  ID_VOTE_LOAD_FAILURE: 'ID_VOTE_LOAD_FAILURE',

  CLOSED_ID_VOTE_LOAD_REQUEST: 'CLOSED_ID_VOTE_LOAD_REQUEST',
  CLOSED_ID_VOTE_LOAD_SUCCESS: 'CLOSED_ID_VOTE_LOAD_SUCCESS',
  CLOSED_ID_VOTE_LOAD_FAILURE: 'CLOSED_ID_VOTE_LOAD_FAILURE',

  INSERT_VOTE: 'INSERT_VOTE',
  REMOVE_VOTE: 'REMOVE_VOTE',

  UPLOAD_COMMENT_REQUEST: 'UPLOAD_COMMENT_REQUEST',
  UPLOAD_COMMENT_SUCCESS: 'UPLOAD_COMMENT_SUCCESS',
  UPLOAD_COMMENT_FAILURE: 'UPLOAD_COMMENT_FAILURE',

  DELETE_COMMENT_REQUEST: 'UPLOAD_COMMENT_REQUEST',
  DELETE_COMMENT_SUCCESS: 'UPLOAD_COMMENT_SUCCESS',
  DELETE_COMMENT_FAILURE: 'UPLOAD_COMMENT_FAILURE',
};
